from typing import Any,Dict,Iterator,List,Protocol,TypeVar,Union
_T=TypeVar('_T')
class PackageMetadata(Protocol):
	def __len__(A):...
	def __contains__(A,item):...
	def __getitem__(A,key):...
	def __iter__(A):...
	def get_all(A,name,failobj=...):'\n        Return all values associated with a possibly multi-valued key.\n        '
	@property
	def json(self):'\n        A JSON-compatible form of the metadata.\n        '
class SimplePath(Protocol):
	'\n    A minimal subset of pathlib.Path required by PathDistribution.\n    '
	def joinpath(A):...
	def __truediv__(A):...
	def parent(A):...
	def read_text(A):...